language: ruby
before_script:
  - cp config/database.yml.travis config/database.yml
script:
- export RAILS_ENV=test
- bundle exec rake db:setup db:migrate
- bundle exec rake spec
after_success:
- if [ $TRAVIS_PULL_REQUEST == false ] && [ $TRAVIS_BRANCH == "master" ]; then
      openssl aes-256-cbc -k $DEPLOY_KEY -in config/deploy_id_rsa_enc_travis -d -a -out config/deploy_id_rsa;
      chmod 600 config/deploy_id_rsa;
      eval `ssh-agent -s`;
      ssh-add config/deploy_id_rsa;
      bundle exec cap production deploy;
      ssh-agent -k;
  fi
env:
  global:
  - secure: NYmv5Fq28AE/vX/p4EJ6B13XRhdBcoUO7EySsZrucOxnIYTBLod4izZZtKJy/qkle2jE/ROGloiJwsi3xdW+hifP4Hb4aPPHRaN2kwNLmbdjKIgUDI3SsdBCzLmhuplTUOs2J/qxWMBzGLtelQT4ED7akaVLovc1trngHaDM0Jl84FzqW5yboJVGK0mxAczMo2vVSZMH6HmGl/aXUS0BHuL3K5c4S28U5jMYB1Wpy4B7vSQY8ok57ixBFqWXCOYaeaLocDN7HVGIK+Pf2AoNvZpXHo0FFmP+t+NcUTDZUpUrOIm1p7YX3M8kazEmWcIsOKy6w1eAFoW9VvQV3K9xxMx3AQVwEk0B4zJbdT2ZqT3dIafmGB6f8U0aC+j2t5NVsGPRQYIYHXG/WCRRqKs9kuh8nOEWsFC/4LictpufKXrS6R15uwhNpdn5jyJ4BXyX3A8SjuINm/IWx5SNb88LAHNbqomf1n8vYhdF/ika4zGVo0uNvAR0H9QulScXmuzl0FCHigQqDinT5lYDFi8ExXE1H4MAKR/axM2H5Ssc0owhBAcSfThGLkseQ3+RtO/ZB0pCuTLT4j4CoLyvxbIg5xZo06qPo4atde55WvAx4ZuhcikZOJXWWb/G7i3LCiS5GvzlFoNq0DGCPULxZ0qQEp8cqa4xAbG5l6j6FLXI9ks=
